[package]
name = "pshenmic-dpp-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
dpp = { git = "https://github.com/owl352/platform", rev = "4aa29b8", default-features = false }
drive = { git = "https://github.com/owl352/platform", rev = "4aa29b8", default-features = false }